name: testojo
favicon: null
layout_spectrum: 0.1657726764678955
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#feffff'
    - '#41114d'
    - '#9f88a6'
    - '#b2b5b9'
    - '#facb99'
  brandStrength: 0.9375
  lightness: 0
  saturation: 0.1875
  rhythmicContrast: 0.9192494158633053
purpose: []
