name: testojo
favicon: null
layout_spectrum: 0.1657726764678955
typography_spectrum: 0.09051154158078134
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7584189211484045
  lightness: 0.11379733891226351
  saturation: 0.7484258057083935
  rhythmicContrast: 0.9192494158633053
purpose: []
